#define _CRT_SECURE_NO_WARNINGS
#include<Windows.h>
#include<stdio.h>
#include<stdlib.h>

#define STATUS int
#define SUCCESS 1
#define FAILURE -1
#define FSEEK_ERROR -1
#define FREAD_ERROR 0

#define CHARACTER 1
#define NOT_CHARACTER 0

#define TIPS_INPUT_FILE_PATH "输入文件路径(建议直接拖进来):"
#define ERROR_ON_OPEN_FILE "文件打开失败!"
#define ERROR_ON_PARSE_DOS "Dos头解析失败!"
#define ERROR_ON_PARSE_PE_SIGNATURE "PE标记解析失败!"
#define ERROR_ON_PARSE_FILE_HEADER "文件头解析失败!"
#define ERROR_ON_PARSE_OTPIONAL_HEADER "可选头解析失败!"
#define ERROR_ON_PARSE_SECTION_HEADER "节表解析失败!"

//PE头
#define OFFSET_ELFANEW 0x3C
#define OFFSET_NT_HEADERS 0xB0
#define OFFSET_MACHINE 0x04
#define OFFSET_NUMBER_OF_SECTIONS 0x06
#define OFFSET_SIZE_OF_OPTIONAL_HEADER 0x14
#define OFFSET_CHARACTERISTICS 0x16
#define OFFSET_MAGIC 0x18
#define OFFSET_ADDRESS_OF_ENTRY_POINT 0x28
#define OFFSET_BASE_OF_CODE 0x2C
#define OFFSET_BASE_OF_DATA 0x30
#define OFFSET_IMAGE_BASE 0x34
#define OFFSET_SECTION_ALIGNMENT 0x38
#define OFFSET_FILE_ALIGNMENT 0x3C
#define OFFSET_SIZE_OF_IMAGE 0x50
#define OFFSET_SIZE_OF_HEADERS 0x54
#define OFFSET_SUBSYSTEM 0x5C
#define OFFSET_NUMBER_OF_RVA_AND_SIZE 0x74
#define OFFSET_DATA_DIRECTORY 0x78

//段/节表
#define SIZE_OF_SECTION 40
#define OFFSET_IMAGE_SECTION_HEADER 0x1A8
#define OFFSET_UNION_MISC 0x08
#define OFFSET_VIRTUAL_ADDRESS 0x0C
#define OFFSET_SIZE_OF_RAW_DATA 0x10
#define OFFSET_POINT_TO_RAW_DATA 0X14
#define OFFSET_SECTION_CHARACTERISTICS 0x24